remove test on private repo

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -64,7 +64,7 @@ jobs:
         run: ls -lrth public-download
 
       - name: Test download latest pre-release
-        uses: ./
+       uses: ./
         with:
           repository: 'robinraju/probable-potato'
           latest: true
@@ -78,22 +78,22 @@ jobs:
         shell: bash
         run: ls -lrth prerelease-downloads
 
-      - name: Test download from a private repo
-        uses: ./
-        id: download-private
-        with:
-          repository: 'robinraju/release-downloader-test'
-          latest: true
-          fileName: '*'
-          tarBall: true
-          zipBall: true
-          extract: true
-          token: ${{ secrets.RELEASE_DOWNLOADER_TEST_TOKEN }}
-          out-file-path: './downloader-test'
+ #     - name: Test download from a private repo
+ #       uses: ./
+ #       id: download-private
+ #       with:
+ #         repository: 'robinraju/release-downloader-test'
+ #         latest: true
+ #         fileName: '*'
+ #         tarBall: true
+ #         zipBall: true
+ #         extract: true
+ #         token: ${{ secrets.RELEASE_DOWNLOADER_TEST_TOKEN }}
+ #         out-file-path: './downloader-test'
 
-      - name: List downloaded files from private repo
-        shell: bash
-        run: ls -lrth downloader-test
+ #     - name: List downloaded files from private repo
+ #       shell: bash
+ #       run: ls -lrth downloader-test
 
       - name: Read output variable set by previous steps
         shell: bash
@@ -103,10 +103,10 @@ jobs:
           else echo "Unable to read output variable from step download-public"; exit 1
           fi
 
-          if [ -n ${{steps.download-private.outputs.tag_name}} ]; then
-            echo ${{steps.download-private.outputs.tag_name}}
-          else echo "Unable to read output variable from step download-private"; exit 1
-          fi
+ #         if [ -n ${{steps.download-private.outputs.tag_name}} ]; then
+ #           echo ${{steps.download-private.outputs.tag_name}}
+ #         else echo "Unable to read output variable from step download-private"; exit 1
+ #         fi
 
           echo "Downloaded files:"
           echo ${{steps.download-public.outputs.downloaded_files}}
